### ISSUE TITLE
some errors below when i do this command : docker-compose build

### ISSUE THREAD

**Issue by Photokeep** [shrimpliu/eos-dawn3-docker#1]
E: Failed to fetch http://mirrors.aliyun.com/ubuntu/pool/main/g/graphviz/libgvc6_2.38.0-12ubuntu2.1_amd64.deb  Hash Sum mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'eos' failed to build: The command '/bin/sh -c echo 'APT::Install-Recommends 0;' >> /etc/apt/apt.conf.d/01norecommends   && echo 'APT::Install-Suggests 0;' >> /etc/apt/apt.conf.d/01norecommends   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y sudo wget curl net-tools ca-certificates unzip doxygen graphviz' returned a non-zero code: 100

**Comment by shrimpliu** [comment]
If you are not in China, you should delete the third line of the file `eos/Dockerfile`, which content is `COPY sources.list /etc/apt/sources.list`
